version: '3.8'
services:
  secondary_postgres:
    image: postgres:latest
    container_name: secondary_postgres_db
    environment:
      POSTGRES_USER: ${SECOND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SECOND_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SECOND_POSTGRES_DB}
    ports:
      - "5434:5432"  # Different host port
    volumes:
      - secondary_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  secondary_postgres_data: